---
 libraries:
   - pr-D0-Z1
   - pr-D0-Z2
   - pr-D0-Z3
   - pr-ld-D2-Z1
   - pr-ld-D2-Z2
   - pr-ld-D2-Z3
   - pr-ld-D3-Z1
   - pr-ld-D3-Z2
   - pr-ld-D3-Z3
   - pr-hd-D2-Z1
   - pr-hd-D2-Z2
   - pr-hd-D2-Z3
   - pr-hd-D3-Z1
   - pr-hd-D3-Z2
   - pr-hd-D3-Z3
