name: deseq2_env

channels:
 - conda-forge
 - bioconda
 - defaults
 - r

dependencies:
  - conda-forge::r-base=4.2.2
  - conda-forge::r-irkernel  #https://irkernel.github.io/installation/
  - bioconda::bioconductor-deseq2=1.38.3  #not available for mac silicon, do Bioconductor
  - bioconda::bioconductor-biocparallel=1.32.5