"""
Author: Stefan Peidli
Aim: Snakemake workflow for PanCov19 Hamster Project.
Date: 19.02.2024
Run: snakemake
DAG: snakemake --forceall --dag | dot -Tpdf > snake_dag.pdf
Rulegraph: snakemake --forceall --rulegraph | dot -Tpdf > snake_rulegraph.pdf
"""
import yaml
from pathlib import Path

import pandas as pd
import numpy as np
from snakemake.utils import min_version

### CONFIGURATION ###
min_version("6.4.1")  # set minimum snakemake version
report: "report/workflow.rst"
configfile: "../configuration/config.yaml"
DIR = Path(config['data_path'])

### RULES ###
rule all:
    input:
        expand(DIR / 'Cov19Hamster_timecourse_integrated_{subset}.h5', 
        subset=['endothelial', 'neutrophils', 'macrophages', 'tcells']),  # 'all'
        # expand(DIR / 'CPU_Cov19Hamster_timecourse_integrated_{subset}.h5', 
        # subset=['endothelial', 'neutrophils', 'macrophages', 'tcells'])  # 'all'

subworkflow Gold_workflow:
    workdir:
        "sub_workflows/MesAur_timecourse"
    snakefile:
        "sub_workflows/MesAur_timecourse/Snakefile"

subworkflow Dwarf_workflow:
    workdir:
        "sub_workflows/PhoRob_timecourse"
    snakefile:
        "sub_workflows/PhoRob_timecourse/Snakefile"

rule gpu_integrate_hamsters:
    """
    Integrate the timecourse data of the two hamster species with scVI and harmony.
    Does the integration on all cells and per specfici cell types to achieve a better integration.
    """
    input:
        pr_timecourse = Dwarf_workflow(DIR / 'PhoRob_timecourse_{subset}.h5'),
        ma_timecourse = Gold_workflow(DIR / 'MesAur_timecourse_{subset}.h5')
    output:
        DIR / 'Cov19Hamster_timecourse_integrated_{subset}.h5'
    resources:
        time='1-00:00:00',
        mem_mb=64000,
        disk_mb=64000,
        partition='gpu-el8',
        slurm_extra="--exclude=gpu[38-39] -G 1 -n 2"
    params:
        max_epochs=10
    conda: 'scvi-env' #"../environments/scvi_env.yaml"
    script: "scripts/integrate_hamsters.py"

# rule cpu_integrate_hamsters:
#     """
#     Integrate the timecourse data of the two hamster species with scVI and harmony.
#     Does the integration on all cells and per specfici cell types to achieve a better integration.
#     """
#     input:
#         pr_timecourse = Dwarf_workflow(DIR / 'PhoRob_timecourse_{subset}.h5'),
#         ma_timecourse = Gold_workflow(DIR / 'MesAur_timecourse_{subset}.h5')
#     output:
#         DIR / 'CPU_Cov19Hamster_timecourse_integrated_{subset}.h5'
#     resources:
#         time='1-00:00:00',
#         mem_mb=64000,
#         disk_mb=64000,
#     params:
#         use_gpu=False,
#         max_epochs=10
#     conda: 'scvi-env' #"../environments/scvi_cpu_env.yaml"
#     script: "scripts/integrate_hamsters.py"